# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
