# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_day_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AlterField(
            model_name='hour',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Day'),
        ),
    ]
