# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180426_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hour',
            options={'ordering': ('location',)},
        ),
    ]
