# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
