# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180426_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
